package net.twerno.carFinder.base.model;

import lombok.Data;
import net.twerno.carFinder.base.utils.extendedType.ExtendedBoolean;

@Data
public class Wyposazenie
{
  private ExtendedBoolean ABS;
  private ExtendedBoolean CD;
  private ExtendedBoolean centralny_zamek;
  private ExtendedBoolean elektryczne_szyby_przednie;
  private ExtendedBoolean elektrycznie_ustawiane_lusterka;
  private ExtendedBoolean immobilizer;;
  private ExtendedBoolean poduszka_powietrzna_kierowcy;
  private ExtendedBoolean poduszka_powietrzna_pasażera;
  private ExtendedBoolean radio_fabryczne;
  private ExtendedBoolean wspomaganie_kierownicy;
  private ExtendedBoolean alarm;
  private ExtendedBoolean alufelgi;
  private ExtendedBoolean asr;
  private ExtendedBoolean asystent_parkowania;
  private ExtendedBoolean asystent_pasa_ruchu;
  private ExtendedBoolean bluetooth;
  private ExtendedBoolean czujnik_deszczu;
  private ExtendedBoolean czujnik_martwego_pola;
  private ExtendedBoolean czujnik_zmierzchu;
  private ExtendedBoolean czujniki_parkowania_przednie;
  private ExtendedBoolean czujniki_parkowania_tylne;
  private ExtendedBoolean dach_panoramiczny;
  private ExtendedBoolean elektrochromatyczne_lusterka_boczne;
  private ExtendedBoolean elektrochromatyczne_lusterko_wsteczne;
  private ExtendedBoolean elektryczne_szyby_tylne;
  private ExtendedBoolean elektrycznie_ustawiane_fotele;
  private ExtendedBoolean esp;
  private ExtendedBoolean gniazdo_AUX;
  private ExtendedBoolean gniazdo_SD;
  private ExtendedBoolean gniazdo_USB;
  private ExtendedBoolean hak;
  private ExtendedBoolean hUD;
  private ExtendedBoolean isofix;
  private ExtendedBoolean kamera_cofania;
  private ExtendedBoolean klimatyzacja_automatyczna;
  private ExtendedBoolean klimatyzacja_czterostrefowa;
  private ExtendedBoolean klimatyzacja_dwustrefowa;
  private ExtendedBoolean klimatyzacja_manualna;
  private ExtendedBoolean komputer_pokładowy;
  private ExtendedBoolean kurtyny_powietrzne;
  private ExtendedBoolean lopatki_zmiany_biegów;
  private ExtendedBoolean mp3;
  private ExtendedBoolean nawigacja_GPS;
  private ExtendedBoolean odtwarzacz_DVD;
  private ExtendedBoolean ogranicznik_prędkości;
  private ExtendedBoolean ogrzewanie_postojowe;
  private ExtendedBoolean podgrzewana_przednia_szyba;
  private ExtendedBoolean podgrzewane_lusterka_boczne;
  private ExtendedBoolean podgrzewane_przednie_siedzenia;
  private ExtendedBoolean podgrzewane_tylne_siedzenia;
  private ExtendedBoolean poduszka_powietrzna_chroniąca_kolana;
  private ExtendedBoolean poduszki_boczne_przednie;
  private ExtendedBoolean poduszki_boczne_tylne;
  private ExtendedBoolean przyciemniane_szyby;
  private ExtendedBoolean radio_niefabryczne;
  private ExtendedBoolean regulowane_zawieszenie;
  private ExtendedBoolean relingi_dachowe;
  private ExtendedBoolean system_StartStop;
  private ExtendedBoolean szyberdach;
  private ExtendedBoolean swiatła_do_jazdy_dziennej;
  private ExtendedBoolean swiatła_LED;
  private ExtendedBoolean swiatła_przeciwmgielne;
  private ExtendedBoolean swiatła_Xenonowe;
  private ExtendedBoolean tapicerka_skórzana;
  private ExtendedBoolean tapicerka_welurowa;
  private ExtendedBoolean tempomat;
  private ExtendedBoolean tempomat_aktywny;
  private ExtendedBoolean tuner_TV;
  private ExtendedBoolean wielofunkcyjna_kierownica;
  private ExtendedBoolean zmieniarka_CD;
}
